language: ruby
rvm:
- 2.2.2
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
deploy:
  provider: heroku
  api_key:
     secure: BwHTBSJQzc2NkKc1buoZsexHRw/U65mOYiaJix4xhKISyaGDAiMPTrJYtVaAE/lHxNrr6VT4cv+liW0sJmpCiHhzrSwdsiO48JOC6efMA3HVBusbG1MFVNY06x8Y7yD7IZb8jD7miJ/yNU92PPePRL7NIQ50r9qBajI6iCVKdvuXd9UjqIjz2G5WrmMKDUxm8IeJT6Ly9fprVoUeIU6sdZTiCn7TIdVvk8gQlJ+D/DdCJEYKf++z4wZjGpfi1eZefk8em00Qp5QpUgIDOGe9VUitdeJ3p/OmkCHnS1Jnz8mDYtqZaKYwrspdo/EQoZNl4V4j1Flj0njej5wxdfLxIXWrv8pIPVVs3+m7sj/+sAQRn6xlH5xDw8uW3yaohF8M8tncG3UE6CjZWGwgVHwSwkiJqEMrUD6GfacXQmMvLcw//9XWE9vgy52/CZv+UqioBZnqECCF168ZuPKV8KiEEdXZwOfweECrd6uc5f3lV9AkT2CxNS/HThRc4lQHrRlMGlBtR9MtP04VAiqQT5mcCPaYN3AlSpxOPMYNUcBXSt/ryHtbFS5kWvzjKwxIAoz2buWBta94vPMZ5cdPSBNRrLUORIJlLUiubegKycc53D7JI6UNj/KNwo2cN7Tk5ZjHrSgklvCNo3HhGq7jSXxcoyxcESl3S5Cvnc63jhk3umA=
  app: minibar
  on:
    repo: dnestoff/miniBAR
