# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cc8df4862fa9ee8e6cb4366586cb6c1cd2921a1bfd30e0543634147061f4864062dd643c370a1cb84812a3196131584fa67d046796b2e30fb662639bc3a9828

test:
  secret_key_base: 7a714473150e60ed2f41f40715b25fc4555f2f14623c678c6daf01c3a868417c79ed9dbffdb0895e0f7e63c9628e467417306cde8607f2a4b7c28a28a6a481f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
